version: '3.8'

services:
  chroma-server:
    build: 
      context: .
      dockerfile: Dockerfile.chroma
    container_name: chroma-server
    environment:
      - CHROMA_MODE=embedded
      - CHROMA_DATA_PATH=/data/chroma
      - CHROMA_COLLECTION_NAME=entity_embeddings
      - CHROMA_EMBEDDING_FUNCTION=ollama
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_EMBEDDING_MODEL=nomic-embed-text
      - FLASK_APP=chroma_server.py
      - FLASK_ENV=production
      - CHROMA_SERVER_HOST=0.0.0.0      - CHROMA_SERVER_PORT=5002
    volumes:
      - chroma_data:/data/chroma
    ports:
      - "5002:5002"
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HTTP_PORT=3000
      - HTTP_HOST=0.0.0.0
      - ARANGO_URL=${ARANGO_URL}
      - ARANGO_DB=${ARANGO_DB}
      - ARANGO_USERNAME=${ARANGO_USERNAME}
      - ARANGO_PASSWORD=${ARANGO_PASSWORD}
      - CHROMA_SERVER_URL=http://chroma-server:5002
      - CHROMA_COLLECTION_NAME=${CHROMA_COLLECTION_NAME:-entity_embeddings}
      - CHROMA_MAX_RETRIES=${CHROMA_MAX_RETRIES:-3}
      - CHROMA_TIMEOUT=${CHROMA_TIMEOUT:-30000}
    depends_on:
      - chroma-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      - ARANGO_URL=http://lsdiedb39c.pagekite.me
      - ARANGO_DB=newsDB2022
      - ARANGO_USERNAME=root
      - ARANGO_PASSWORD=i-0172f1f969c7548c4
      - HTTP_PORT=3000
      - HTTP_HOST=0.0.0.0
      - CHROMA_SERVER_URL=http://chroma-server:5002
      - CHROMA_COLLECTION_NAME=entity_embeddings
      - CHROMA_MAX_RETRIES=3
      - CHROMA_TIMEOUT=30000
    ports:
      - "3000:3000"
    depends_on:
      - chroma-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  chroma_data:
  ollama_data:
